---
services:

  # --- ITTools - Collection of handy tools for IT professionals
  ittools:
    container_name: ittools
    env_file: .env
    ports:
        - '8888:80'
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tools.entrypoints=http"
      - "traefik.http.routers.tools.rule=Host(`${TOOLS_DOMAIN}`)"
      - "traefik.http.middlewares.tools-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tools.middlewares=tools-https-redirect"
      - "traefik.http.routers.tools-secure.entrypoints=https"
      - "traefik.http.routers.tools-secure.rule=Host(`${TOOLS_DOMAIN}`)"
      - "traefik.http.routers.tools-secure.middlewares=authentik@file"
      - "traefik.http.routers.tools-secure.tls=true"
      - "traefik.http.routers.tools.service=tools"
      - "traefik.http.services.tools.loadbalancer.server.port=80"

  # --- VSCode Server - Code Server
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
      DEFAULT_WORKSPACE: /workspace
    env_file: .env
    volumes:
      - /mnt/data/appdata/code-server:/config:rw
      - /home/beheerder/docker:/workspace:rw
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.entrypoints=http"
      - "traefik.http.routers.code.rule=Host(`${VSCODE_DOMAIN}`)"
      - "traefik.http.middlewares.code-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.code.middlewares=code-https-redirect"
      - "traefik.http.routers.code-secure.entrypoints=https"
      - "traefik.http.routers.code-secure.rule=Host(`${VSCODE_DOMAIN}`)"
      - "traefik.http.routers.code-secure.middlewares=authentik@file"
      - "traefik.http.routers.code-secure.tls=true"
      - "traefik.http.routers.code.service=code"
      - "traefik.http.services.code.loadbalancer.server.port=8443"
    security_opt:
      - no-new-privileges:true

  # --- TrueCommand - TrueCommand is a single pane of glass management system for FreeNAS and TrueNAS
  truecommand:
    image: ixsystems/truecommand:latest
    container_name: truecommand
    restart: unless-stopped
    env_file: .env
    volumes:
      - /mnt/data/appdata/truecommand:/data:rw
    # ports:
    #   - 8880:80
      # - 8843:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.truecommand.entrypoints=http"
      - "traefik.http.routers.truecommand.rule=Host(`${TRUECOMMAND_DOMAIN}`)"
      - "traefik.http.middlewares.truecommand-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.truecommand.middlewares=truecommand-https-redirect"
      - "traefik.http.routers.truecommand-secure.entrypoints=https"
      - "traefik.http.routers.truecommand-secure.rule=Host(`${TRUECOMMAND_DOMAIN}`)"
      - "traefik.http.routers.truecommand-secure.tls=true"
      - "traefik.http.routers.truecommand.service=truecommand"
      - "traefik.http.services.truecommand.loadbalancer.server.port=80"
    networks:
      - frontend

networks:
  frontend:
    external: true