---
services:
  ittools:
    container_name: ittools
    env_file: .env
    ports:
        - '8888:80'
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tools.entrypoints=http"
      - "traefik.http.routers.tools.rule=Host(`${TOOLS_DOMAIN}`)"
      - "traefik.http.middlewares.tools-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tools.middlewares=tools-https-redirect"
      - "traefik.http.routers.tools-secure.entrypoints=https"
      - "traefik.http.routers.tools-secure.rule=Host(`${TOOLS_DOMAIN}`)"
      - "traefik.http.routers.tools-secure.middlewares=authentik@file"
      - "traefik.http.routers.tools-secure.tls=true"
      - "traefik.http.routers.tools.service=tools"
      - "traefik.http.services.tools.loadbalancer.server.port=80"
networks:
  frontend:
    external: true